version: '3.9'
services:
  crawler:
    build: .
    container_name: crawler_server
    ports:
      - 8080:80
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - type: bind
        source: ./static
        target: /usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - crawler
    restart: unless-stopped
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: unless-stopped
volumes:
  redis_data: