version: '3.9'
services:
  crawler:
    build: .
    container_name: crawler_server
    volumes:
      - index_files:/usr/src/app/index
    ports:
      - 8080:80
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - index_files:/usr/share/nginx/index:ro
      - type: bind
        source: ./static
        target: /usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - crawler
    restart: unless-stopped
volumes:
  index_files: